/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStudentBillsRouteImport } from './routes/dashboard/student-bills'
import { Route as DashboardSppRouteImport } from './routes/dashboard/spp'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardFeeTypesRouteImport } from './routes/dashboard/fee-types'
import { Route as DashboardClassBillsRouteImport } from './routes/dashboard/class-bills'
import { Route as DashboardBeasiswaRouteImport } from './routes/dashboard/beasiswa'
import { Route as DashboardStudentBillsIndexRouteImport } from './routes/dashboard/student-bills/index'
import { Route as DashboardClassBillsIndexRouteImport } from './routes/dashboard/class-bills/index'
import { Route as DashboardStudentBillsStudentIdRouteImport } from './routes/dashboard/student-bills/$studentId'
import { Route as DashboardClassBillsClassIdIndexRouteImport } from './routes/dashboard/class-bills/$classId/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentBillsRoute = DashboardStudentBillsRouteImport.update({
  id: '/student-bills',
  path: '/student-bills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSppRoute = DashboardSppRouteImport.update({
  id: '/spp',
  path: '/spp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeeTypesRoute = DashboardFeeTypesRouteImport.update({
  id: '/fee-types',
  path: '/fee-types',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassBillsRoute = DashboardClassBillsRouteImport.update({
  id: '/class-bills',
  path: '/class-bills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBeasiswaRoute = DashboardBeasiswaRouteImport.update({
  id: '/beasiswa',
  path: '/beasiswa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentBillsIndexRoute =
  DashboardStudentBillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardStudentBillsRoute,
  } as any)
const DashboardClassBillsIndexRoute =
  DashboardClassBillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardClassBillsRoute,
  } as any)
const DashboardStudentBillsStudentIdRoute =
  DashboardStudentBillsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => DashboardStudentBillsRoute,
  } as any)
const DashboardClassBillsClassIdIndexRoute =
  DashboardClassBillsClassIdIndexRouteImport.update({
    id: '/$classId/',
    path: '/$classId/',
    getParentRoute: () => DashboardClassBillsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/beasiswa': typeof DashboardBeasiswaRoute
  '/dashboard/class-bills': typeof DashboardClassBillsRouteWithChildren
  '/dashboard/fee-types': typeof DashboardFeeTypesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/spp': typeof DashboardSppRoute
  '/dashboard/student-bills': typeof DashboardStudentBillsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/student-bills/$studentId': typeof DashboardStudentBillsStudentIdRoute
  '/dashboard/class-bills/': typeof DashboardClassBillsIndexRoute
  '/dashboard/student-bills/': typeof DashboardStudentBillsIndexRoute
  '/dashboard/class-bills/$classId/': typeof DashboardClassBillsClassIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/beasiswa': typeof DashboardBeasiswaRoute
  '/dashboard/fee-types': typeof DashboardFeeTypesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/spp': typeof DashboardSppRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/student-bills/$studentId': typeof DashboardStudentBillsStudentIdRoute
  '/dashboard/class-bills': typeof DashboardClassBillsIndexRoute
  '/dashboard/student-bills': typeof DashboardStudentBillsIndexRoute
  '/dashboard/class-bills/$classId': typeof DashboardClassBillsClassIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/beasiswa': typeof DashboardBeasiswaRoute
  '/dashboard/class-bills': typeof DashboardClassBillsRouteWithChildren
  '/dashboard/fee-types': typeof DashboardFeeTypesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/spp': typeof DashboardSppRoute
  '/dashboard/student-bills': typeof DashboardStudentBillsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/student-bills/$studentId': typeof DashboardStudentBillsStudentIdRoute
  '/dashboard/class-bills/': typeof DashboardClassBillsIndexRoute
  '/dashboard/student-bills/': typeof DashboardStudentBillsIndexRoute
  '/dashboard/class-bills/$classId/': typeof DashboardClassBillsClassIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/beasiswa'
    | '/dashboard/class-bills'
    | '/dashboard/fee-types'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/spp'
    | '/dashboard/student-bills'
    | '/dashboard/'
    | '/dashboard/student-bills/$studentId'
    | '/dashboard/class-bills/'
    | '/dashboard/student-bills/'
    | '/dashboard/class-bills/$classId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/beasiswa'
    | '/dashboard/fee-types'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/spp'
    | '/dashboard'
    | '/dashboard/student-bills/$studentId'
    | '/dashboard/class-bills'
    | '/dashboard/student-bills'
    | '/dashboard/class-bills/$classId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/beasiswa'
    | '/dashboard/class-bills'
    | '/dashboard/fee-types'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/spp'
    | '/dashboard/student-bills'
    | '/dashboard/'
    | '/dashboard/student-bills/$studentId'
    | '/dashboard/class-bills/'
    | '/dashboard/student-bills/'
    | '/dashboard/class-bills/$classId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student-bills': {
      id: '/dashboard/student-bills'
      path: '/student-bills'
      fullPath: '/dashboard/student-bills'
      preLoaderRoute: typeof DashboardStudentBillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/spp': {
      id: '/dashboard/spp'
      path: '/spp'
      fullPath: '/dashboard/spp'
      preLoaderRoute: typeof DashboardSppRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fee-types': {
      id: '/dashboard/fee-types'
      path: '/fee-types'
      fullPath: '/dashboard/fee-types'
      preLoaderRoute: typeof DashboardFeeTypesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/class-bills': {
      id: '/dashboard/class-bills'
      path: '/class-bills'
      fullPath: '/dashboard/class-bills'
      preLoaderRoute: typeof DashboardClassBillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/beasiswa': {
      id: '/dashboard/beasiswa'
      path: '/beasiswa'
      fullPath: '/dashboard/beasiswa'
      preLoaderRoute: typeof DashboardBeasiswaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student-bills/': {
      id: '/dashboard/student-bills/'
      path: '/'
      fullPath: '/dashboard/student-bills/'
      preLoaderRoute: typeof DashboardStudentBillsIndexRouteImport
      parentRoute: typeof DashboardStudentBillsRoute
    }
    '/dashboard/class-bills/': {
      id: '/dashboard/class-bills/'
      path: '/'
      fullPath: '/dashboard/class-bills/'
      preLoaderRoute: typeof DashboardClassBillsIndexRouteImport
      parentRoute: typeof DashboardClassBillsRoute
    }
    '/dashboard/student-bills/$studentId': {
      id: '/dashboard/student-bills/$studentId'
      path: '/$studentId'
      fullPath: '/dashboard/student-bills/$studentId'
      preLoaderRoute: typeof DashboardStudentBillsStudentIdRouteImport
      parentRoute: typeof DashboardStudentBillsRoute
    }
    '/dashboard/class-bills/$classId/': {
      id: '/dashboard/class-bills/$classId/'
      path: '/$classId'
      fullPath: '/dashboard/class-bills/$classId/'
      preLoaderRoute: typeof DashboardClassBillsClassIdIndexRouteImport
      parentRoute: typeof DashboardClassBillsRoute
    }
  }
}

interface DashboardClassBillsRouteChildren {
  DashboardClassBillsIndexRoute: typeof DashboardClassBillsIndexRoute
  DashboardClassBillsClassIdIndexRoute: typeof DashboardClassBillsClassIdIndexRoute
}

const DashboardClassBillsRouteChildren: DashboardClassBillsRouteChildren = {
  DashboardClassBillsIndexRoute: DashboardClassBillsIndexRoute,
  DashboardClassBillsClassIdIndexRoute: DashboardClassBillsClassIdIndexRoute,
}

const DashboardClassBillsRouteWithChildren =
  DashboardClassBillsRoute._addFileChildren(DashboardClassBillsRouteChildren)

interface DashboardStudentBillsRouteChildren {
  DashboardStudentBillsStudentIdRoute: typeof DashboardStudentBillsStudentIdRoute
  DashboardStudentBillsIndexRoute: typeof DashboardStudentBillsIndexRoute
}

const DashboardStudentBillsRouteChildren: DashboardStudentBillsRouteChildren = {
  DashboardStudentBillsStudentIdRoute: DashboardStudentBillsStudentIdRoute,
  DashboardStudentBillsIndexRoute: DashboardStudentBillsIndexRoute,
}

const DashboardStudentBillsRouteWithChildren =
  DashboardStudentBillsRoute._addFileChildren(
    DashboardStudentBillsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardBeasiswaRoute: typeof DashboardBeasiswaRoute
  DashboardClassBillsRoute: typeof DashboardClassBillsRouteWithChildren
  DashboardFeeTypesRoute: typeof DashboardFeeTypesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSppRoute: typeof DashboardSppRoute
  DashboardStudentBillsRoute: typeof DashboardStudentBillsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBeasiswaRoute: DashboardBeasiswaRoute,
  DashboardClassBillsRoute: DashboardClassBillsRouteWithChildren,
  DashboardFeeTypesRoute: DashboardFeeTypesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSppRoute: DashboardSppRoute,
  DashboardStudentBillsRoute: DashboardStudentBillsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
